[package]
name = "sub-screen-player"
description = "Drive small USB sub-displays (\"sub screens\") from macOS, Linux and Windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "ssp"
path = "src/main.rs"

[dependencies]
ssp-core.workspace = true
ssp-server.workspace = true
anyhow.workspace = true
clap.workspace = true
directories.workspace = true
image.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ureq.workspace = true
url.workspace = true

[target.'cfg(windows)'.dependencies]
winreg.workspace = true

[lints]
workspace = true
